audit_header: false
title: Central Michigan's Best Real Estate Training
description: Mary Peacock, a top Real Estate Agent in Central Michigan, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/mary-peacock-17957153289
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Mary Peacock
  title:
  license_number:
  about_markdown: |
    Mary Peacock has provided buyers and sellers with trusted support and service for years. Her experience in the real estate market will be your best asset in making smart and economically sound real estate decisions. She prides herself on offering the very best customer service to her clients. If you are selling, Mary will ensure that your home gets the attention necessary to properly promote it in the marketplace. For buyers, she will exhaust all of her resources to assist in finding the perfect home you've been looking for. If you want someone that will be there full-time, all the time - and will provide direct support for your real estate needs - look no further than Mary Peacock.
  market: Central Michigan
  brand: Peacock Real Estate
  brokerage:
  address: 18030 3 Mile Rd. Morley, MI 49336
  phone: 231.856.4456
  phone_type:
  phone2:
  phone2_type:
  email: Mary@PeacockRealEstate.com
  url: https://PeacockRealEstate.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Mid-Michigan-Real-Estate-Mastermind-2299874053626202/
  linkedin_url: https://www.linkedin.com/pub/mary-peacock/43/263/3b2
  youtube_url: https://www.youtube.com/channel/UCIVA0e2lla9fgs-5QcTJHsw
  twitter_url: https://twitter.com/thepeacockteam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/central-michigan-real-estate-podcast-with-mary-peacock/id1447969357?mt=2

podcast:
  title: '-- MARKET -- Real Estate Mentoring Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'Looking for more ways to grow your real estate business and increase your income? Mary Peacock, founder of Peacock Real Estate, shares her success stories and strategies to help you on your path to a successful real estate career. For even more information and tips, go to MidMichiganRealEstateCareers.com, and follow her mentoring Facebook page https://www.facebook.com/midmichiganrealestatecareers. Ready to take your career to the next level? Peacock Real Estate provides exceptional training and mentoring to help your real estate business thrive! Call 231-856-4456 for more information!'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  hero_image_path2: /img/background2.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#00aaa6'
  theme_color: '#00628c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
